### Get Application
GET http://localhost:5001/api/v1/organisers/programmes/1/applications
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjo2LCJuYW1lIjoiRGF2aWQgSGFzc2VsaG9yZiIsImVtYWlsIjoidGVzdDEyMzQ1NjdAZ21haWwuY29tIiwiY29udGFjdF9ubyI6bnVsbCwiYWNjb3VudF90eXBlIjoib3JnYW5pc2VyIiwianNvbl90b2tlbklEIjoiazVUREVudTBUeTJ0Zlc1MnpZbmdaQSIsImlhdCI6MTY5MDQ2NDAzNCwiZXhwIjoxNjkwNDY3NjM0LCJqdGkiOiJrNVRERW51MFR5MnRmVzUyelluZ1pBIn0.kSLUnTO1nzCXwgVBhKjRPM0484QEuRevBF4hl5FCu4U

### Login
POST http://localhost:5001/api/v1/login
Accept: application/json
Content-Type: application/json

{
    "email": "test1234567@gmail.com",
    "password": "123457"
}

### Get User
GET http://localhost:5001/api/v1/users/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjo2LCJuYW1lIjoiRGF2aWQgSGFzc2VsaG9yZiIsImVtYWlsIjoidGVzdDEyMzQ1NjdAZ21haWwuY29tIiwiY29udGFjdF9ubyI6bnVsbCwiYWNjb3VudF90eXBlIjoib3JnYW5pc2VyIiwianNvbl90b2tlbklEIjoiazVUREVudTBUeTJ0Zlc1MnpZbmdaQSIsImlhdCI6MTY5MDQ2NDAzNCwiZXhwIjoxNjkwNDY3NjM0LCJqdGkiOiJrNVRERW51MFR5MnRmVzUyelluZ1pBIn0.kSLUnTO1nzCXwgVBhKjRPM0484QEuRevBF4hl5FCu4U

### Search Programmes by Name
GET http://localhost:5001/api/v1/programmes/search-by-name/est%20P
Accept: application/json
Content-Type: application/json


### Search Programmes by Name
POST http://localhost:5001/api/v1/organisers/programmes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoxMCwibmFtZSI6IkRldjIiLCJlbWFpbCI6ImRldjJAZ21haWwuY29tIiwiY29udGFjdF9ubyI6bnVsbCwiYWNjb3VudF90eXBlIjoib3JnYW5pc2VyIiwianNvbl90b2tlbklEIjoiOExVRWtqNldRcktZMlFuVFk2ZWd0USIsImlhdCI6MTY5MDU0ODE0OSwiZXhwIjoxNjkwNTQ5MDQ5LCJqdGkiOiI4TFVFa2o2V1FyS1kyUW5UWTZlZ3RRIn0.IGMt2RLhMA8azn6T5FSulwdKqSSQUIWsZltcNFVB5vY

{
    "name": "test2",
    "description": "qwerty",
    "deadline": "2023-10-10",
    "matching_criteria": "[]",
    "programmeEnd": "2023-12-12"
}


### Search Programmes by Name
POST http://localhost:5001/api/v1/organisers/programmes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoxMCwibmFtZSI6IkRldjIiLCJlbWFpbCI6ImRldjJAZ21haWwuY29tIiwiY29udGFjdF9ubyI6bnVsbCwiYWNjb3VudF90eXBlIjoib3JnYW5pc2VyIiwianNvbl90b2tlbklEIjoiOExVRWtqNldRcktZMlFuVFk2ZWd0USIsImlhdCI6MTY5MDU0ODE0OSwiZXhwIjoxNjkwNTQ5MDQ5LCJqdGkiOiI4TFVFa2o2V1FyS1kyUW5UWTZlZ3RRIn0.IGMt2RLhMA8azn6T5FSulwdKqSSQUIWsZltcNFVB5vY

{
    "name": "testprog3"
    "description": "asdfg"
    "deadline": "2023-09-09",
    "matching_criteria": "nothing",
    "programmeEnd": "2023-11-11"
}